### PR TITLE
Complete rewrite of Minimap

### PR DESCRIPTION
**Pull request by msteiger**
This is an almost complete rewrite of this module (no version update included yet). It replaces the small-scale, but multi-axis view with a single, but large-scale top-down view. See the screenshot.

The world is sampled similar to MarchingCubes and updated when block events occur. The result is cached in framebuffer objects and rendered as tiles filling the entire minimap area.

Requires https://github.com/MovingBlocks/Terasology/pull/1931
Would benefit from https://github.com/MovingBlocks/Terasology/issues/1926

### CODE REVIEW

**Comment by msteiger** [comment]
Drawing on a cache image twice causes the entire image to be black -> need to investigate first.
I suspect it's the FBO bind/unbind methods

**Comment by Cervator** [comment]
Yeah I just gave it a quick test and just get a black map with the player arrow :(

The description in module.txt could use an update too, it still mentions the differing axes. And we still have the slider for changing layer - should that stay, maybe just tied to height? It currently seems to toggle twice for each press of numpad + / -, once on key press once on key release

**Comment by msteiger** [comment]
The black squares after block modification bug should be fixed with https://github.com/MovingBlocks/Terasology/pull/1941

**Comment by Cervator** [comment]
Ah cool. Worth noting I didn't have that PR present :-) Will merge after release and re-test

**Pull request merged**
